### ISSUE TITLE
Building on ArchLinux fails

### ISSUE THREAD

**Issue by fyrak1s** [themanyone/3mfthumb#1]
Hi, trying to build on arch.

Despite `lib3mf` installed on my system I am getting:
```sh
g++ -g -Wall  -I/usr/include/lib3mf  -c 3mfthumb.cpp -o 3mfthumb.o
3mfthumb.cpp:24:10: fatal error: lib3mf_implicit.hpp: No such file or directory
   24 | #include "lib3mf_implicit.hpp"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [Makefile:8: all] Error 1
```

The requested file `lib3mf_implicit.hpp` is there however. Look here https://archlinux.org/packages/extra/x86_64/lib3mf/files/. Seems like it should look under the subdir "Bindings"?

Thanks in advance and great job so far. Cool project.

**Comment by themanyone** [comment]
Huh, weird. Okay. I changed the location to Bindings/Cpp. Should build now. :)

**Comment by fyrak1s** [comment]
Some issues with the makefile:
`cp -lf 3mf.thumbnailer /home/k/.local/share/thumbnailers/` <- not every user is called `k` ;)

Also, I have a pretty fresh arch install, and had to create the `bin` directory (`~/.local/bin`) manually since it did not exist.

The Thumbnailers dir does not exist here neither so the script fails:
`cp: cannot create hard link '/home/nuci/.local/share/thumbnailers/' to '3mf.thumbnailer': No such file or directory`

I am not an expert but I think usually it's done like this:
```
mkdir -p ~/.local/bin
mkdir -p ~/.local/share/thumbnailers/
```
This creates those dirs if they dont exist. Maybe there is a better way but calling this prior should work. That's how I did it in my Dockerfiles.

Also I think professionals™ use `$HOME` instead of `~` (apparently it is more portable https://stackoverflow.com/questions/5930671/why-use-home-over-tilde-in-a-shell-script) :P
I do not really care, but just pointing that out :D 

After fixing those minor things it worked! :) ty

**Comment by themanyone** [comment]
Oh my. The install section is atrocious. I'm going to look up makefiles and do that a little better.
